language: python

python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"

branches:
  only:
    - staging
    - trying
    - master

install: "python setup.py build"

script: "python test.py"
